# Generated by Django 4.2.7 on 2025-09-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator', '0002_article_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='priority_label',
            field=models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority'), ('minimal', 'Minimal Priority')], default='minimal', max_length=20),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['priority_label', '-published_date'], name='news_aggreg_priorit_90a19c_idx'),
        ),
    ]
